<a href="https://colab.research.google.com/github/SAKETH-ADILLA/Machine-Learning/blob/main/Assessment_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#First Assessment

##Perform arithmetic operations on NumPy arrays.

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
add_result = arr1 + arr2
print("Addition:", add_result)
sub_result = arr1 - arr2
print("Subtraction:", sub_result)
mul_result = arr1 * arr2
print("Multiplication:", mul_result)
div_result = arr1 / arr2
print("Division:", div_result)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


##Write a script to compute the mean and standard deviation of a NumPy array.


In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
mean_value = np.mean(arr)
print(f"Mean: {mean_value}")
std_deviation = np.std(arr)
print(f"Standard Deviation: {std_deviation}")


Mean: 30.0
Standard Deviation: 14.142135623730951


##Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [3]:
import numpy as np
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


##Reshape the array into a 2x4 matrix.


In [5]:
import numpy as np
arr = np.arange(10, 46 , 5)
reshaped_arr = arr.reshape(2, 4)
print(reshaped_arr)


[[10 15 20 25]
 [30 35 40 45]]


##Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [6]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = arr[1:, :2]
print("Sub-matrix containing the last two rows and first two columns:")
print(sub_matrix)
arr[arr > 4] = 0
print("\nArray after replacing elements greater than 4 with 0:")
print(arr)


Sub-matrix containing the last two rows and first two columns:
[[4 5]
 [7 8]]

Array after replacing elements greater than 4 with 0:
[[1 2 3]
 [4 0 0]
 [0 0 0]]


##Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add_result = a + b
print("Element-wise Addition:", add_result)
mul_result = a * b
print("Element-wise Multiplication:", mul_result)
div_result = a / b
print("Element-wise Division:", div_result)


Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


## Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [11]:
import numpy as np
arr = np.random.rand(4, 4)
mean_value = np.mean(arr)
print("Mean of the entire array:", mean_value)
max_value = np.max(arr)
print("Maximum value of the entire array:", max_value)
sum_elements = np.sum(arr)
print("Sum of all elements:", sum_elements)


Mean of the entire array: 0.5816356830100999
Maximum value of the entire array: 0.8516237255946544
Sum of all elements: 9.306170928161599


##Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = (arr + 10) * 2
print("Result:", result)


Result: [22 24 26 28]


##Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [13]:
import numpy as np
arr = np.random.randint(1, 101, size=(3, 4, 5))
print("Original Array:\n", arr)
second_layer = arr[1]
print("\nSecond Layer (2D Array at index 1):\n", second_layer)
first_two_rows_last_three_columns = arr[:, :2, -3:]
print("\nFirst Two Rows and Last Three Columns from Each Layer:\n", first_two_rows_last_three_columns)
arr[arr % 3 == 0] = -1
print("\nArray After Replacing Elements Divisible by 3 with -1:\n", arr)


Original Array:
 [[[ 62  23  62  37  93]
  [ 80  60  50  22  25]
  [ 76  72  74  62  19]
  [100  36  76  39  13]]

 [[ 88  43  21  19  14]
  [ 12  60  42  76  70]
  [ 39  28  54  93  36]
  [ 74  44  41   3  68]]

 [[ 90  51   1  45  59]
  [ 76  44  42  93  86]
  [100  85  96  41  58]
  [ 91   8  84  18  75]]]

Second Layer (2D Array at index 1):
 [[88 43 21 19 14]
 [12 60 42 76 70]
 [39 28 54 93 36]
 [74 44 41  3 68]]

First Two Rows and Last Three Columns from Each Layer:
 [[[62 37 93]
  [50 22 25]]

 [[21 19 14]
  [42 76 70]]

 [[ 1 45 59]
  [42 93 86]]]

Array After Replacing Elements Divisible by 3 with -1:
 [[[ 62  23  62  37  -1]
  [ 80  -1  50  22  25]
  [ 76  -1  74  62  19]
  [100  -1  76  -1  13]]

 [[ 88  43  -1  19  14]
  [ -1  -1  -1  76  70]
  [ -1  28  -1  -1  -1]
  [ 74  44  41  -1  68]]

 [[ -1  -1   1  -1  59]
  [ 76  44  -1  -1  86]
  [100  85  -1  41  58]
  [ 91   8  -1  -1  -1]]]


##Work with broadcasting and advanced operations in NumPy.
Create a NumPy array arr of shape (3, 3) with random integers between  
1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [14]:
import numpy as np
arr = np.random.randint(1, 21, size=(3, 3))
print("Original Array:\n", arr)
row_means = []
for row in arr:
    row_means.append(np.mean(row))
normalized_arr = np.array([row - mean for row, mean in zip(arr, row_means)])
print("\nRow-wise Normalized Array:\n", normalized_arr)
squared_arr = arr * arr
print("\nSquared Array:\n", squared_arr)
flattened_arr = arr.flatten()
top_3_indices_flat = np.argsort(flattened_arr)[-3:]
top_3_indices = np.unravel_index(top_3_indices_flat, arr.shape)
print("\nIndices of Top 3 Maximum Values:\n", top_3_indices)


Original Array:
 [[ 7 13  9]
 [12  3 15]
 [19  9 13]]

Row-wise Normalized Array:
 [[-2.66666667  3.33333333 -0.66666667]
 [ 2.         -7.          5.        ]
 [ 5.33333333 -4.66666667 -0.66666667]]

Squared Array:
 [[ 49 169  81]
 [144   9 225]
 [361  81 169]]

Indices of Top 3 Maximum Values:
 (array([2, 1, 2]), array([2, 2, 0]))
